package io.hafa.rmapikt

import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.delay
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.util.UUID
import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream

private const val GENERATION_BASE_MS = 25L
private const val PAGEDATA_SUFFIX = ".pagedata"
private const val DEFAULT_MARGINS = 125

/**
 * how a document is scaled to the screen
 *
 * A sealed type rather than an enum plus six loose numbers: the custom fit needs all of
 * them and the other modes need none, so pairing a mode with the wrong fields is not
 * representable instead of being silently ignored.
 */
public sealed interface Zoom {
    /** fit the whole page on screen */
    public data object BestFit : Zoom

    /** scale so the page height fills the screen */
    public data object FitToHeight : Zoom

    /** scale so the page width fills the screen */
    public data object FitToWidth : Zoom

    /** an explicitly positioned and scaled view */
    public data class Custom(
        /** the scale, which reMarkable generally keeps between 0.5 and 5 */
        public val scale: Double,
        /** the horizontal centre, in device pixels from the page's centre */
        public val centerX: Double,
        /** the vertical centre, in device pixels from the page's top */
        public val centerY: Double,
        /** the rendered page width in device pixels */
        public val pageWidth: Double,
        /** the rendered page height in device pixels, `heightPoints * dpi / 72` */
        public val pageHeight: Double,
        /** the orientation this view was configured in */
        public val orientation: Orientation,
    ) : Zoom
}

/** how a `put*` builds the document it commits */
public data class PutOptions(
    /** where the document lands */
    public val parent: Parent = Parent.Root,
    /** whether the document starts starred; the wire calls this `pinned` */
    public val starred: Boolean = false,
    /** the thumbnail page; -1 means the last visited */
    public val coverPageNumber: Int = -1,
    /** the authors recorded in the document's own metadata */
    public val authors: List<String>? = null,
    /** the title recorded in the document's own metadata, independent of its name */
    public val title: String? = null,
    /** the publication date */
    public val publicationDate: String? = null,
    /** the publisher */
    public val publisher: String? = null,
    /** pen settings and similar, passed through untouched */
    public val extraMetadata: Map<String, String> = emptyMap(),
    /** the render font; empty selects the device default */
    public val fontName: String = "",
    /** the line height; -1 selects the device default */
    public val lineHeight: Int = -1,
    /** the page margin in pixels */
    public val margins: Int = DEFAULT_MARGINS,
    /** the page orientation */
    public val orientation: Orientation = Orientation.Portrait,
    /** tags to apply, which are given the current timestamp */
    public val tags: List<String>? = null,
    /** how text is aligned */
    public val textAlignment: TextAlignment = TextAlignment.Justify,
    /** the font size */
    public val textScale: Double = 1.0,
    /** how the document is scaled to the screen */
    public val zoom: Zoom = Zoom.BestFit,
    /** the adaptive contrast filter */
    public val viewBackgroundFilter: BackgroundFilter? = null,
)

/** what to override when restoring an archive with [RemarkableClient.importArchive] */
public data class ImportOptions(
    /** where the restored document lands; keeps the archived parent when null */
    public val parent: Parent? = null,
    /** the restored document's name; keeps the archived name when null */
    public val visibleName: String? = null,
    /**
     * the id to restore under
     *
     * A fresh id is generated by default so restoring into the same account does not
     * collide with the original; pass the archived id to overwrite it instead.
     */
    public val id: ItemId? = null,
)

/**
 * what a bulk operation did
 *
 * The two halves are separate so a caller cannot mistake a partial result for a complete
 * one: a ref that was not in the root index is reported rather than quietly dropped.
 */
public data class BulkResult(
    /** each ref that moved, mapped to a ref at its new state */
    public val moved: Map<ItemRef, ItemRef>,
    /** the refs that were not in the root index, and so were left alone */
    public val notFound: Set<ItemRef>,
)

/**
 * the reMarkable cloud, in terms of documents rather than hashes
 *
 * Every mutating call is a read-modify-write against the account's root index, so two
 * clients editing at once will race. Losing that race is normal, and this client handles
 * it by re-reading and re-applying the change up to
 * [SessionOptions.maxGenerationRetries] times before giving up with a
 * [GenerationException].
 */
@Suppress("TooManyFunctions")
public class RemarkableClient internal constructor(
    private val rawClient: RawRemarkableClient,
    private val maxGenerationRetries: Int,
) {
    /** the low-level api, for operations this one doesn't cover */
    public val raw: RawRemarkableClient get() = rawClient

    @Volatile
    private var lastRoot: RootInfo? = null

    /**
     * re-reads the root index, discarding this client's cached view of it
     *
     * Only needed to observe someone else's change; this client's own writes keep its view
     * current, and a lost race is retried without any help.
     */
    public suspend fun refreshRoot(): RootInfo = rawClient.getRootHash().also { lastRoot = it }

    private suspend fun root(): RootInfo = lastRoot ?: refreshRoot()

    private suspend fun commitRoot(hash: FileHash, generation: Long) {
        try {
            val updated = rawClient.putRootHash(hash, generation)
            lastRoot = lastRoot?.copy(hash = updated.hash, generation = updated.generation)
        } catch (error: GenerationException) {
            // the cached view is now known to be behind, so the retry must re-read
            lastRoot = null
            throw error
        }
    }

    /**
     * Re-runs [operation] when it loses a race for the root index.
     *
     * The caller must mint any ids and timestamps *before* calling this, so that a retry
     * re-uploads the identical blobs instead of orphaning a fresh set on every attempt.
     */
    private suspend fun <T> withGenerationRetry(operation: suspend () -> T): T {
        var attempt = 0
        while (true) {
            try {
                return operation()
            } catch (error: GenerationException) {
                if (attempt >= maxGenerationRetries) {
                    throw error
                }
                delay(backoffMillis(attempt, GENERATION_BASE_MS))
                attempt++
            }
        }
    }

    private suspend fun rootEntries(): List<RawEntry> =
        rawClient.getEntries(ROOT_SCHEMA, root().hash).entries

    private suspend fun uploadAll(staged: List<StagedFile>): Unit = coroutineScope {
        staged.map { async { rawClient.upload(it) } }.awaitAll()
    }

    /** Adds a freshly built item to the root index. */
    private suspend fun commitNewItem(entry: RawEntry) = withGenerationRetry {
        val current = root()
        val entries = rootEntries() + entry
        val rootEntry = rawClient.stageEntries(ROOT_LIST, entries, SchemaVersion.V4)
        rawClient.upload(rootEntry)
        commitRoot(rootEntry.entry.hash, current.generation)
    }

    /** every item's id and hash, without fetching any metadata */
    public suspend fun listRefs(): List<ItemRef> =
        rootEntries().map { ItemRef(ItemId(it.id), it.hash) }

    private suspend fun componentEntries(ref: ItemRef): List<RawEntry> =
        rawClient.getEntries("${ref.id.value}$SCHEMA_SUFFIX", ref.hash).entries

    private suspend fun component(ref: ItemRef, which: DocumentComponent): RawEntry =
        componentEntries(ref).firstOrNull { it.id.endsWith(which.suffix) }
            ?: throw ComponentNotFoundException(ref, which)

    /** the item's `.content` file */
    public suspend fun getContent(ref: ItemRef): Content =
        component(ref, DocumentComponent.Content).let { rawClient.getContent(it.id, it.hash) }

    /** the item's `.metadata` file */
    public suspend fun getMetadata(ref: ItemRef): Metadata =
        component(ref, DocumentComponent.Metadata).let { rawClient.getMetadata(it.id, it.hash) }

    /**
     * the item's `.template` file
     *
     * Only template items have one; a template's `.content` is empty, so this is where its
     * definition lives.
     *
     * @throws ComponentNotFoundException if the item is not a template
     */
    public suspend fun getTemplate(ref: ItemRef): TemplateDefinition =
        component(ref, DocumentComponent.Template).let {
            decodeWire(TemplateDefinition.serializer(), rawClient.getText(it.id, it.hash), "template")
        }

    /** @throws ComponentNotFoundException if the item has no pdf */
    public suspend fun getPdf(ref: ItemRef): ByteArray =
        component(ref, DocumentComponent.Pdf).let { rawClient.getBlob(it.id, it.hash) }

    /** @throws ComponentNotFoundException if the item has no epub */
    public suspend fun getEpub(ref: ItemRef): ByteArray =
        component(ref, DocumentComponent.Epub).let { rawClient.getBlob(it.id, it.hash) }

    private suspend fun documentFiles(ref: ItemRef): Map<String, ByteArray> = coroutineScope {
        componentEntries(ref)
            .map { entry -> async { entry.id to rawClient.getBlob(entry.id, entry.hash) } }
            .awaitAll()
            .toMap()
    }

    /**
     * the undecoded `.rm` page files, keyed by page id
     *
     * These hold the pen strokes, and reMarkable's own notebooks consist of nothing else.
     * The page ids match [DocumentContent.pages], so the result can be ordered by that
     * list. Pass each value to [parseRmFile] for the strokes; parsing per page rather than
     * for the whole document lets one unreadable page be handled without losing the rest.
     */
    public suspend fun getRawPages(ref: ItemRef): Map<String, ByteArray> = coroutineScope {
        val prefix = "${ref.id.value}/"
        componentEntries(ref)
            .filter { it.id.startsWith(prefix) && it.id.endsWith(RM_SUFFIX) }
            .map { entry ->
                async {
                    entry.id.removePrefix(prefix).removeSuffix(RM_SUFFIX) to
                        rawClient.getBlob(entry.id, entry.hash)
                }
            }
            .awaitAll()
            .toMap()
    }

    /**
     * every component file of the item, packed into one zip archive
     *
     * This is a transfer format for round-tripping a document through [importArchive]; it
     * is not the document itself. For the pdf or epub use [getPdf]/[getEpub]; for the
     * component files as data, walk the item with [raw].
     */
    public suspend fun exportArchive(ref: ItemRef): ByteArray = zipArchive(documentFiles(ref))

    /**
     * restores an archive produced by [exportArchive]
     *
     * Every archived file is re-uploaded under a fresh document id unless
     * [ImportOptions.id] says otherwise. This takes an archive, not a pdf: to add a pdf use
     * [putPdf] or [uploadPdf].
     */
    public suspend fun importArchive(
        archive: ByteArray,
        options: ImportOptions = ImportOptions(),
    ): ItemRef {
        val files = readArchive(archive)
        val metadataPath = files.keys.firstOrNull { it.endsWith(METADATA_SUFFIX) }
            ?: throw ValidationException("archive did not contain a .metadata file")
        require(!metadataPath.dropLast(METADATA_SUFFIX.length).contains('/')) {
            "unexpected nested .metadata path '$metadataPath'"
        }
        val oldId = metadataPath.dropLast(METADATA_SUFFIX.length)
        // minted before the retry loop so a retry re-uploads identical blobs
        val newId = options.id ?: ItemId(UUID.randomUUID().toString())
        val lastModified = System.currentTimeMillis().toString()

        val schemaVersion = root().schemaVersion
        val staged = files.map { (path, bytes) ->
            require(path.startsWith(oldId)) {
                "archived file '$path' did not start with '$oldId'"
            }
            // every archived path is prefixed with the document's own id, so restoring under
            // a new id means rewriting that prefix on all of them
            val newPath = newId.value + path.removePrefix(oldId)
            if (path == metadataPath) {
                rawClient.stageMetadata(
                    newPath,
                    restoredMetadata(bytes, options, lastModified),
                )
            } else {
                rawClient.stageFile(newPath, bytes)
            }
        }
        val documentEntry = rawClient.stageEntries(
            newId.value,
            staged.map { it.entry },
            schemaVersion,
        )
        uploadAll(staged + documentEntry)
        commitNewItem(documentEntry.entry)
        return ItemRef(newId, documentEntry.entry.hash)
    }

    private fun restoredMetadata(
        archivedBytes: ByteArray,
        options: ImportOptions,
        lastModified: String,
    ): Metadata {
        val archived = decodeWire(
            Metadata.serializer(),
            archivedBytes.toString(Charsets.UTF_8),
            "archived metadata",
        )
        return archived.copy(
            parent = options.parent ?: archived.parent,
            visibleName = options.visibleName ?: archived.visibleName,
            lastModified = lastModified,
        )
    }

    /**
     * builds a pdf document locally and commits it through the sync protocol
     *
     * This constructs every component file itself, so it takes the full [PutOptions] and is
     * sensitive to the root generation. Its counterpart [uploadPdf] hands the file to the
     * server instead: fewer options, but the server does the work.
     */
    public suspend fun putPdf(
        visibleName: String,
        pdf: ByteArray,
        options: PutOptions = PutOptions(),
    ): ItemRef = putDocumentFile(visibleName, FileType.Pdf, pdf, options)

    /** the epub counterpart of [putPdf]; see it for how this differs from [uploadEpub] */
    public suspend fun putEpub(
        visibleName: String,
        epub: ByteArray,
        options: PutOptions = PutOptions(),
    ): ItemRef = putDocumentFile(visibleName, FileType.Epub, epub, options)

    private suspend fun putDocumentFile(
        visibleName: String,
        fileType: FileType,
        bytes: ByteArray,
        options: PutOptions,
    ): ItemRef {
        // every minted value is resolved here, before any retry, so re-running the commit
        // reuses the same blobs rather than orphaning a new set each time
        val id = UUID.randomUUID().toString()
        val now = System.currentTimeMillis()
        val metadata = newDocumentMetadata(visibleName, options, now)
        val content = newDocumentContent(fileType, bytes.size, options, now)

        val schemaVersion = root().schemaVersion
        val staged = listOf(
            rawClient.stageContent("$id$CONTENT_SUFFIX", content),
            rawClient.stageMetadata("$id$METADATA_SUFFIX", metadata),
            rawClient.stageText("$id$PAGEDATA_SUFFIX", "\n"),
            rawClient.stageFile("$id.${fileType.extension}", bytes),
        )
        val itemEntry = rawClient.stageEntries(id, staged.map { it.entry }, schemaVersion)
        uploadAll(staged + itemEntry)
        commitNewItem(itemEntry.entry)
        return ItemRef(ItemId(id), itemEntry.entry.hash)
    }

    private fun newDocumentMetadata(
        visibleName: String,
        options: PutOptions,
        now: Long,
    ): Metadata = Metadata(
        visibleName = visibleName,
        parent = options.parent,
        pinned = options.starred,
        type = EntryType.Document,
        lastModified = now.toString(),
        createdTime = now.toString(),
        lastOpened = "0",
        lastOpenedPage = 0,
    )

    private fun newDocumentContent(
        fileType: FileType,
        sizeInBytes: Int,
        options: PutOptions,
        now: Long,
    ): DocumentContent = DocumentContent(
        coverPageNumber = options.coverPageNumber,
        documentMetadata = DocumentMetadata(
            authors = options.authors,
            title = options.title,
            publicationDate = options.publicationDate,
            publisher = options.publisher,
        ),
        extraMetadata = options.extraMetadata,
        fileType = fileType,
        fontName = options.fontName,
        lineHeight = options.lineHeight,
        orientation = options.orientation,
        // the device wants a page count of 1 and a matching page list even though it has
        // not rendered the file yet; anything else produces a document it won't open
        pageCount = 1,
        originalPageCount = 1,
        pages = listOf(UUID.randomUUID().toString()),
        redirectionPageMap = listOf(0),
        pageTags = emptyList(),
        textAlignment = options.textAlignment,
        textScale = options.textScale,
        zoomMode = options.zoom.mode,
        customZoomScale = (options.zoom as? Zoom.Custom)?.scale,
        customZoomCenterX = (options.zoom as? Zoom.Custom)?.centerX,
        customZoomCenterY = (options.zoom as? Zoom.Custom)?.centerY,
        customZoomPageWidth = (options.zoom as? Zoom.Custom)?.pageWidth,
        customZoomPageHeight = (options.zoom as? Zoom.Custom)?.pageHeight,
        customZoomOrientation = (options.zoom as? Zoom.Custom)?.orientation,
        tags = options.tags
            ?.let { names -> Tags.Structured(names.map { Tag(it, now) }) }
            ?: Tags.Empty,
        formatVersion = 1,
        margins = options.margins,
        sizeInBytes = sizeInBytes.toString(),
        viewBackgroundFilter = options.viewBackgroundFilter,
    )

    /** creates a folder through the sync protocol; the counterpart of [uploadFolder] */
    public suspend fun putFolder(visibleName: String, parent: Parent = Parent.Root): ItemRef {
        val id = UUID.randomUUID().toString()
        val now = System.currentTimeMillis().toString()
        val metadata = Metadata(
            visibleName = visibleName,
            parent = parent,
            pinned = false,
            type = EntryType.Collection,
            lastModified = now,
            createdTime = now,
        )
        val schemaVersion = root().schemaVersion
        val staged = listOf(
            rawClient.stageContent("$id$CONTENT_SUFFIX", CollectionContent()),
            rawClient.stageMetadata("$id$METADATA_SUFFIX", metadata),
        )
        val itemEntry = rawClient.stageEntries(id, staged.map { it.entry }, schemaVersion)
        uploadAll(staged + itemEntry)
        commitNewItem(itemEntry.entry)
        return ItemRef(ItemId(id), itemEntry.entry.hash)
    }

    /**
     * hands a pdf to the server's ingestion endpoint, which builds the document
     *
     * Robust and simple, but offers no control over how the document is rendered. Use
     * [putPdf] when you need [PutOptions].
     */
    public suspend fun uploadPdf(visibleName: String, pdf: ByteArray): ItemRef =
        rawClient.uploadFile(visibleName, pdf, UploadKind.Pdf)

    /** the epub counterpart of [uploadPdf]; see [putEpub] for the alternative */
    public suspend fun uploadEpub(visibleName: String, epub: ByteArray): ItemRef =
        rawClient.uploadFile(visibleName, epub, UploadKind.Epub)

    /** creates a folder through the ingestion endpoint; the counterpart of [putFolder] */
    public suspend fun uploadFolder(visibleName: String): ItemRef =
        rawClient.uploadFile(visibleName, ByteArray(0), UploadKind.Folder)

    /**
     * rewrites a document's `.content`, leaving its `.metadata` alone
     *
     * @throws ValidationException if the item at [ref] is not a document
     */
    public suspend fun updateDocumentContent(
        ref: ItemRef,
        update: (DocumentContent) -> DocumentContent,
    ): ItemRef = editContent(ref, EntryType.Document) { update(it.orFail(ref.hash)) }

    /** rewrites a folder's `.content`; see [updateDocumentContent] */
    public suspend fun updateCollectionContent(
        ref: ItemRef,
        update: (CollectionContent) -> CollectionContent,
    ): ItemRef = editContent(ref, EntryType.Collection) { update(it.orFail(ref.hash)) }

    private suspend fun editContent(
        ref: ItemRef,
        expected: EntryType,
        update: (Content) -> Content,
    ): ItemRef = withGenerationRetry {
        val current = root()
        val entries = rootEntries().toMutableList()
        val index = entries.indexOfFirst { it.hash == ref.hash }
        if (index < 0) {
            throw HashNotFoundException(ref.hash)
        }
        val item = entries[index]
        val itemRef = ref
        val metadata = getMetadata(itemRef)
        if (metadata.type != expected) {
            throw ValidationException(
                "expected a ${expected.name} at '${ref.hash.hex}' but found a ${metadata.type.name}",
            )
        }

        val componentEntries = componentEntries(itemRef).toMutableList()
        val contentIndex = componentEntries.indexOfFirst { it.id.endsWith(CONTENT_SUFFIX) }
        if (contentIndex < 0) {
            throw ComponentNotFoundException(itemRef, DocumentComponent.Content)
        }
        val contentEntry = componentEntries[contentIndex]
        // read the raw text rather than the decoded value: a firmware quirk key the api
        // deliberately doesn't model still has to be written back exactly as it arrived
        val original = rawClient.getText(contentEntry.id, contentEntry.hash)
        val updated = update(decodeContent(original))
        val stagedContent = rawClient.stageText(
            contentEntry.id,
            encodeContent(updated, contentQuirks(original)),
        )
        componentEntries[contentIndex] = stagedContent.entry

        val itemIndex = rawClient.stageEntries(item.id, componentEntries, current.schemaVersion)
        entries[index] = itemIndex.entry
        val rootEntry = rawClient.stageEntries(ROOT_LIST, entries, SchemaVersion.V4)
        uploadAll(listOf(stagedContent, itemIndex, rootEntry))
        commitRoot(rootEntry.entry.hash, current.generation)
        ItemRef(ref.id, itemIndex.entry.hash)
    }

    /**
     * Rewrites one item's `.metadata`, returning its new index entry and what to upload.
     *
     * Bumping `version` and setting `metadatamodified` is what tells the device the change
     * came from somewhere other than itself.
     */
    private suspend fun stageMetadataEdit(
        item: RawEntry,
        schemaVersion: SchemaVersion,
        update: (Metadata) -> Metadata,
    ): Pair<StagedFile, List<StagedFile>> {
        val components = componentEntries(ItemRef(ItemId(item.id), item.hash)).toMutableList()
        val index = components.indexOfFirst { it.id.endsWith(METADATA_SUFFIX) }
        if (index < 0) {
            throw ComponentNotFoundException(
                ItemRef(ItemId(item.id), item.hash),
                DocumentComponent.Metadata,
            )
        }
        val entry = components[index]
        val current = rawClient.getMetadata(entry.id, entry.hash)
        val updated = update(current).let {
            it.copy(version = (it.version ?: 0) + 1, metadatamodified = true)
        }
        val staged = rawClient.stageMetadata(entry.id, updated)
        components[index] = staged.entry
        val itemIndex = rawClient.stageEntries(item.id, components, schemaVersion)
        return itemIndex to listOf(staged, itemIndex)
    }

    /**
     * writes an item's `.metadata`
     *
     * The general form of [move], [rename] and [star], and the only way to reach the rest of
     * [Metadata] — `lastOpened`, `lastOpenedPage`, `deleted`, `source`, the flags.
     *
     * [Metadata.version] and [Metadata.metadatamodified] are overwritten regardless of what
     * [metadata] carries: they are how the device is told a change came from elsewhere.
     */
    public suspend fun setMetadata(ref: ItemRef, metadata: Metadata): ItemRef =
        editMetadata(ref) { metadata }

    private suspend fun editMetadata(
        ref: ItemRef,
        update: (Metadata) -> Metadata,
    ): ItemRef = withGenerationRetry {
        val current = root()
        val entries = rootEntries().toMutableList()
        val index = entries.indexOfFirst { it.hash == ref.hash }
        if (index < 0) {
            throw HashNotFoundException(ref.hash)
        }
        val (itemIndex, staged) = stageMetadataEdit(entries[index], current.schemaVersion, update)
        entries[index] = itemIndex.entry
        val rootEntry = rawClient.stageEntries(ROOT_LIST, entries, SchemaVersion.V4)
        uploadAll(staged + rootEntry)
        commitRoot(rootEntry.entry.hash, current.generation)
        ItemRef(ref.id, itemIndex.entry.hash)
    }

    /** moves an item, returning a ref to the moved item */
    public suspend fun move(ref: ItemRef, parent: Parent): ItemRef =
        editMetadata(ref) { it.copy(parent = parent) }

    /** moves an item to the trash; reMarkable has no hard delete */
    public suspend fun trash(ref: ItemRef): ItemRef = move(ref, Parent.Trash)

    /** renames an item, returning a ref to the renamed item */
    public suspend fun rename(ref: ItemRef, visibleName: String): ItemRef =
        editMetadata(ref) { it.copy(visibleName = visibleName) }

    /** stars or unstars an item; the wire calls this `pinned` */
    public suspend fun star(ref: ItemRef, starred: Boolean): ItemRef =
        editMetadata(ref) { it.copy(pinned = starred) }

    /**
     * moves many items in one root write
     *
     * A ref that isn't in the current root index is reported in [BulkResult.notFound]
     * rather than moved, because a partial move is a normal outcome of racing another
     * client and should not fail the whole batch.
     */
    public suspend fun bulkMove(refs: Collection<ItemRef>, parent: Parent): BulkResult =
        withGenerationRetry {
            val current = root()
            val wanted = refs.associateBy { it.hash }
            val (toUpdate, untouched) = rootEntries().partition { it.hash in wanted }

            val edits = coroutineScope {
                toUpdate.map { item ->
                    async {
                        item.hash to stageMetadataEdit(item, current.schemaVersion) {
                            it.copy(parent = parent)
                        }
                    }
                }.awaitAll()
            }

            val entries = untouched + edits.map { (_, edit) -> edit.first.entry }
            val rootEntry = rawClient.stageEntries(ROOT_LIST, entries, SchemaVersion.V4)
            uploadAll(edits.flatMap { (_, edit) -> edit.second } + rootEntry)
            commitRoot(rootEntry.entry.hash, current.generation)

            val moved = edits.associate { (old, edit) ->
                wanted.getValue(old) to ItemRef(wanted.getValue(old).id, edit.first.entry.hash)
            }
            BulkResult(moved = moved, notFound = (refs.toSet() - moved.keys))
        }

    /** trashes many items in one root write; see [bulkMove] */
    public suspend fun bulkTrash(refs: Collection<ItemRef>): BulkResult =
        bulkMove(refs, Parent.Trash)

    /** the cache as a string, to hand to [SessionOptions.cache] in a later session */
    public fun dumpCache(): String = rawClient.dumpCache()

    /** empties the cache */
    public fun clearCache(): Unit = rawClient.clearCache()

    /** drops every cached hash the root index can no longer reach */
    public suspend fun pruneCache() {
        val current = root()
        val unreachable = rawClient.cachedHashes().toMutableSet()
        unreachable.remove(current.hash.hex)

        var frontier = listOf(rawClient.getEntries(ROOT_SCHEMA, current.hash).entries)
        while (frontier.isNotEmpty()) {
            val reached = frontier.flatten()
            reached.forEach { unreachable.remove(it.hash.hex) }
            frontier = descend(reached.filter { it.subfiles > 0 })
        }
        unreachable.forEach(rawClient::forget)
    }

    private suspend fun descend(parents: List<RawEntry>): List<List<RawEntry>> = coroutineScope {
        parents
            .map { async { rawClient.getEntries("${it.id}$SCHEMA_SUFFIX", it.hash).entries } }
            .awaitAll()
    }
}

/**
 * Narrows decoded content to the variant the caller asked to edit.
 *
 * An item's `.metadata` says what kind of thing it is, but the `.content` file is told
 * apart by which keys it has, and the two can disagree: a document whose content is `{}`
 * decodes as a collection. Checking the metadata alone would leave an unchecked cast to
 * fail as a ClassCastException, where the api promises a ValidationException.
 */
private inline fun <reified T : Content> Content.orFail(hash: FileHash): T = this as? T
    ?: throw ValidationException(
        "the content at '${hash.hex}' is ${this::class.simpleName}, " +
            "not the ${T::class.simpleName} its metadata implies",
    )

/** the wire's flat mode value for a [Zoom] */
private val Zoom.mode: ZoomMode
    get() = when (this) {
        Zoom.BestFit -> ZoomMode.BestFit
        Zoom.FitToHeight -> ZoomMode.FitToHeight
        Zoom.FitToWidth -> ZoomMode.FitToWidth
        is Zoom.Custom -> ZoomMode.CustomFit
    }

private fun zipArchive(files: Map<String, ByteArray>): ByteArray {
    val out = ByteArrayOutputStream()
    ZipOutputStream(out).use { zip ->
        for ((name, bytes) in files) {
            zip.putNextEntry(ZipEntry(name))
            zip.write(bytes)
            zip.closeEntry()
        }
    }
    return out.toByteArray()
}

private fun readArchive(archive: ByteArray): Map<String, ByteArray> {
    val files = LinkedHashMap<String, ByteArray>()
    ZipInputStream(ByteArrayInputStream(archive)).use { zip ->
        while (true) {
            val entry = zip.nextEntry ?: break
            if (!entry.isDirectory) {
                files[entry.name] = zip.readBytes()
            }
            zip.closeEntry()
        }
    }
    return files
}
